version: '3.6'
services:
  node:
    container_name: registration_frontend_node
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - $GLS_GATE_HOST:$GLS_GATE_PORT:$GLS_GATE_PORT
    environment:
    - GLS_METRICS_HOST
    - GLS_METRICS_PORT
    - GLS_GATE_HOST
    - GLS_GATE_PORT
